// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GET(arg1) {
  return window['go']['main']['App']['GET'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Lifestyle(arg1) {
  return window['go']['main']['App']['Lifestyle'](arg1);
}
