// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GET(arg1:string):Promise<any>;

export function Greet(arg1:string):Promise<string>;

export function Lifestyle(arg1:string):Promise<main.RespDate>;
